Fix Sonatype Lift findings
eclipse-hono/hono pull request #3395
Opened 2022-08-26 08:44 UTC by sophokles73

DO NOT MERGE YET
this is a test

2022-09-05 10:08 UTC, calohmn requested changes

2022-09-05 10:08 UTC, calohmn commented on tests/src/test/resources/artemis/launch.sh
> +# We want the sed command to replace the actual occurrence of "cp $AMQ_HOME/conf/*"
This sentence doesn't seem correct - see comment lines above (`replacing [...] with [...]`).

2022-09-05 10:08 UTC, calohmn commented on service-base/src/main/java/org/eclipse/hono/service/auth/ValidityOnlyTrustManagerFactory.java
> +                establishment and or request processing instead.
nit: `and/or`

2022-09-06 06:34 UTC, calohmn commented on core/src/main/java/org/eclipse/hono/config/AbstractConfig.java
>      protected final String getPassword(final String purpose, final String value) {
It would be good to apply the modification also to the other places where `PATH_TRAVERSAL_IN` warnings get suppressed.

2022-09-06 06:45 UTC, sophokles73 commented on core/src/main/java/org/eclipse/hono/config/AbstractConfig.java
>      protected final String getPassword(final String purpose, final String value) {
That is true

2022-09-06 07:12 UTC, calohmn approved these changes
LGTM

2022-09-06 09:13 UTC, merged